name: Run Hudl UI Tests Securely (Headless Firefox)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    env:
      BROWSER: firefox  # 🔥 Run tests in headless Firefox
      HEADLESS: "true"  # ✅ Ensure headless mode is enabled

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox & Required Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          sudo apt-get install -y xvfb libgtk-3-0 libdbus-glib-1-2 libasound2
          firefox --version  # ✅ Print installed Firefox version
          which firefox  # ✅ Verify Firefox binary location

      - name: Run UI Tests (Headless Firefox)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # ✅ Start virtual display
          export DISPLAY=:99  # ✅ Set display environment variable
          pytest hudl/ -m login_test --html=reports/report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/report.html
