
name: Debug Hudl UI Tests

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Current Directory
        run: pwd

      - name: List Files in Repository
        run: ls -R

      - name: Show Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List Installed Python Packages
        run: pip list

      - name: Find Test Files
        run: find . -name "test_*.py" -o -name "*_test.py"

      - name: Check Pytest Test Discovery
        run: pytest --collect-only
