
name: Run Hudl UI Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests-chrome:
    runs-on: ubuntu-latest  # Use Ubuntu for consistency

    env:
      BROWSER: chrome  # Runs tests in Chrome

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Secrets as Environment Variables
        env:
          REGISTERED_EMAIL: ${{ secrets.REGISTERED_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: echo "Secrets loaded"

      - name: Run UI Tests on Chrome
        run: pytest -n auto --html=report-chrome.html --self-contained-html --title="Hudl UI Tests - Chrome"

      - name: Upload Test Report (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: test-report-chrome
          path: report-chrome.html

  ui-tests-firefox:
    runs-on: ubuntu-latest  # Use the same environment
    needs: ui-tests-chrome  # Runs after Chrome tests complete

    env:
      BROWSER: firefox  # Runs tests in Firefox

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Secrets as Environment Variables
        env:
          REGISTERED_EMAIL: ${{ secrets.REGISTERED_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: echo "Secrets loaded"

      - name: Run UI Tests on Firefox
        run: pytest -n auto --html=report-firefox.html --self-contained-html --title="Hudl UI Tests - Firefox"

      - name: Upload Test Report (Firefox)
        uses: actions/upload-artifact@v4
        with:
          name: test-report-firefox
          path: report-firefox.html
