
name: Run Hudl UI Tests Securely

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, headlesschrome, headlessfirefox]
        exclude:
          - os: windows-latest
            browser: safari
          - os: ubuntu-latest
            browser: safari
    env:
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug - Installed Python Packages
        run: pip list

      - name: Install Browsers on Windows
        if: runner.os == 'Windows'
        run: |
          choco install googlechrome firefox -y
          refreshenv

      - name: Debug - Verify WebDriver Installation
        run: |
          which chromedriver || echo "ChromeDriver not found!"
          which geckodriver || echo "GeckoDriver not found!"

      - name: Debug - Check Collected Tests
        run: pytest --collect-only

      - name: Run UI Tests in Parallel
        run: |
          pytest -m login_test -n auto --html=report-${{ matrix.browser }}.html --self-contained-html --title="Hudl UI Tests - ${{ matrix.browser }}" || \
          pytest -n auto --html=report-${{ matrix.browser }}.html --self-contained-html --title="Hudl UI Tests - ${{ matrix.browser }}"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.browser }}
          path: report-${{ matrix.browser }}.html

      - name: Upload Failed Test Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: Reports_Images_Failed_Tests
